### PR TITLE
DataSatOslo - Added possibility to set top and bottom margin for spon…

### PR DESCRIPTION
**Pull request by RuneORakeie**
…sor logos. Added 2 new sponsors

### CODE REVIEW

**Comment by spaghettidba** [comment]
Hey man! I see that you changed the way the site generator works...
I'm totally ok with that, but I guess it needs stronger testing compared to editing the page/yml/whatever of the single event.
@SQLDBAWithABeard thoughts?

**Comment by SQLDBAWithABeard** [comment]
The logic looks fine as there is a default and we also have an additional sponsor benefits from Atlanta, which looks good

https://github.com/dataplat/DataSaturdays/blob/b92fc6bc294c873c40a096f983f72747c2b54394/_layouts/post.html#L118
https://datasaturdays.com/2022-10-01-datasaturday0028/#sponsors

It would be good to get those added into the GH Action and issue as well

**Comment by spaghettidba** [comment]
So I guess we can merge it?

**Comment by RuneORakeie** [comment]
> Hey man! I see that you changed the way the site generator works... I'm totally ok with that, but I guess it needs stronger testing compared to editing the page/yml/whatever of the single event. @SQLDBAWithABeard thoughts?

That is correct. I have made quite a few changes in order to get the type event page and info we wanted to present.

These are the changes I have made over the course of a few months:
* New attribute to show/hide the top-logo: `hide-toplogo: true/false`
* New attribute to show/hide the join room section: `hide-join-room-section: true/false`
* New attribute that opens the event registration in a new tab: `open-registration-new-tab: true/false`
* Added a new section for pre-con's which adds a new menu-item: `precondescription`
* Added a new attribute that enables a new button for people to download the Sessionize schedule app for the event:  `scheduleapp`
* Added a new attribute that shows the venue physical location using Google Maps: `venuemap`
* Added a new attribute that shows the events Code of Conduct which also enables a new menu item: `codeofconduct`

I think that was it. As @SQLDBAWithABeard mentions the new attributes for margins for sponsor logos have a default setting and that also applies for all the other functionality I have added

**Review by SQLDBAWithABeard — APPROVED** [review]
I approve this change with all the power of greyskull

**Comment by SQLDBAWithABeard** [comment]
> > Hey man! I see that you changed the way the site generator works... I'm totally ok with that, but I guess it needs stronger testing compared to editing the page/yml/whatever of the single event. @SQLDBAWithABeard thoughts?
> 
> That is correct. I have made quite a few changes in order to get the type event page and info we wanted to present.
> 
> These are the changes I have made over the course of a few months:
> 
> * New attribute to show/hide the top-logo: `hide-toplogo: true/false`
> * New attribute to show/hide the join room section: `hide-join-room-section: true/false`
> * New attribute that opens the event registration in a new tab: `open-registration-new-tab: true/false`
> * Added a new section for pre-con's which adds a new menu-item: `precondescription`
> * Added a new attribute that enables a new button for people to download the Sessionize schedule app for the event:  `scheduleapp`
> * Added a new attribute that shows the venue physical location using Google Maps: `venuemap`
> * Added a new attribute that shows the events Code of Conduct which also enables a new menu item: `codeofconduct`
> 
> I think that was it. As @SQLDBAWithABeard mentions the new attributes for margins for sponsor logos have a default setting and that also applies for all the other functionality I have added

I love all of this @RuneORakeie - be awesome to incorporate all of this and the sponsor thing I whipped up for Atlanta and make that all the default

**Comment by RuneORakeie** [comment]
Yes @SQLDBAWithABeard we should. Both for the template and also updating the docs explaining the purpose of them. I addition I would also like to incorporate Daniel Hutmacher solution for the raffle. He built one for DataSat Stockholm.
I have more time after DataMinds Connect to look into it.

**Pull request merged**
