### PR TITLE
Major changes, sponsor logs and pre-con

### PR DESCRIPTION
**Pull request by DBIA-Dev**
Please update to the main branch.

### CODE REVIEW

**Review by spaghettidba — APPROVED** [review]

**Review by spaghettidba — APPROVED** [review]

**Comment by spaghettidba** [comment]
@SQLDBAWithABeard It looks like I can't update this branch from main. That's weird. Can you please take a look?

**Comment by SQLDBAWithABeard** [comment]
I can but not for a while.  
Am in airport right now without a laptop. 
I'll look in the browser when I get to the Netherlands 😁

**Comment by SQLDBAWithABeard** [comment]
@DBIA-Dev please can you update your code from the main branch so that we can check these changes

**Comment by DBIA-Dev** [comment]
Done

**Comment by DBIA-Dev** [comment]
I can't seem to see the changes on the site?

**Pull request merged**
